# Generated by Django 4.0.5 on 2022-07-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('common_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('petals', models.IntegerField()),
                ('size', models.IntegerField()),
                ('leaf_arrangement', models.CharField(max_length=100)),
                ('habitat', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=250)),
            ],
        ),
    ]
