# Generated by Django 4.0.5 on 2022-07-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='size',
            field=models.IntegerField(verbose_name='Size in Inches'),
        ),
    ]
