# Generated by Django 4.0.5 on 2022-07-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sighting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('use', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateField(verbose_name='Sighting Date'),
        ),
    ]
