# Generated by Django 4.0.5 on 2022-07-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_use_alter_sighting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='uses',
            field=models.ManyToManyField(to='main_app.use'),
        ),
    ]
